# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(465, 362)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 446, 318))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 7)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 4, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 4, 1, 1)
        self.location = QtWidgets.QLineEdit(self.widget)
        self.location.setEnabled(False)
        self.location.setObjectName("location")
        self.gridLayout.addWidget(self.location, 2, 5, 1, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.widget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout.addWidget(self.radioButton_2, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 5, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 7, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 2, 2, 11, 1)
        self.step_bu = QtWidgets.QPushButton(self.widget)
        self.step_bu.setObjectName("step_bu")
        self.gridLayout.addWidget(self.step_bu, 12, 4, 1, 1)
        self.sequences = QtWidgets.QLineEdit(self.widget)
        self.sequences.setEnabled(False)
        self.sequences.setObjectName("sequences")
        self.gridLayout.addWidget(self.sequences, 4, 4, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 2, 6, 12, 1)
        self.execute = QtWidgets.QPushButton(self.widget)
        self.execute.setObjectName("execute")
        self.gridLayout.addWidget(self.execute, 12, 5, 1, 1)
        self.sequence_range = QtWidgets.QLineEdit(self.widget)
        self.sequence_range.setObjectName("sequence_range")
        self.gridLayout.addWidget(self.sequence_range, 8, 1, 1, 1)
        self.radioButton_1 = QtWidgets.QRadioButton(self.widget)
        self.radioButton_1.setObjectName("radioButton_1")
        self.gridLayout.addWidget(self.radioButton_1, 2, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 13, 0, 1, 6)
        self.execute_detail = QtWidgets.QTextBrowser(self.widget)
        self.execute_detail.setEnabled(False)
        self.execute_detail.setObjectName("execute_detail")
        self.gridLayout.addWidget(self.execute_detail, 5, 4, 7, 2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 2, 0, 11, 1)
        self.sequence_num = QtWidgets.QLineEdit(self.widget)
        self.sequence_num.setObjectName("sequence_num")
        self.gridLayout.addWidget(self.sequence_num, 6, 1, 1, 1)
        self.product_seq = QtWidgets.QPushButton(self.widget)
        self.product_seq.setObjectName("product_seq")
        self.gridLayout.addWidget(self.product_seq, 12, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 2, 3, 11, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.product_seq.clicked.connect(self.product)
        self.step_bu.clicked.connect(self.single_step)
        self.execute.clicked.connect(self.action)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def product(self):
        pass

    def single_step(self):
        pass

    def action(self):
        pass

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "请求序列"))
        self.label_4.setText(_translate("MainWindow", "当前磁臂位置"))
        self.radioButton_2.setText(_translate("MainWindow", "SCAN"))
        self.label.setText(_translate("MainWindow", "生成序列数量"))
        self.label_2.setText(_translate("MainWindow", "生成序列范围"))
        self.step_bu.setText(_translate("MainWindow", "单步执行"))
        self.execute.setText(_translate("MainWindow", "全部执行"))
        self.radioButton_1.setText(_translate("MainWindow", "SSTF"))
        self.product_seq.setText(_translate("MainWindow", "点我生成"))
